### ISSUE TITLE
Timezone for timestamps

### ISSUE THREAD

**Issue by wasade** [caporaso-lab-graveyard/clout#19]
This would be useful when matching up error output to other systems such as thebeast where some files are downloaded from

**Comment by gregcaporaso** [comment]
+1

**Comment by jairideout** [comment]
Just checked and timestamps are in UTC, which seems reasonable since we have people viewing these results from different timezones. I also verified that the EC2 instances have the correct time, so I don't think any changes need to be made to Clout or qiime-deploy.

I think this issue is resolved, so I'm closing it. If there's any objections, please reopen the issue.
