### ISSUE TITLE
Make -u/--user option optional

### ISSUE THREAD

**Issue by jairideout** [caporaso-lab-graveyard/clout#22]
`-u/--user` is currently a required option. This should be made optional so that Clout will default to running commands as root on the EC2 instance (this is `sshmaster`'s default behavior as well).

The reasoning is that we have currently maxed out hard drive space on /home/ubuntu/ in the nightly test run (as more projects are being added). We need to be able to store data and run the tests from /mnt/. I think defaulting to root login is a good solution. The alternative is logging into the instance as the specified user (e.g. `ubuntu`) and chowning/chmoding /mnt/ (since root owns it).

**Comment by gregcaporaso** [comment]
I'm a little concerned about defaulting to running clout as `root` as it doesn't accurately reflect how we're installing QIIME in AWS (we usually install under the `ubuntu` user's account). I feel like it has the potential to not catch issues that we might otherwise catch (for example, if code was writing to a directory that normal users wouldn't have access to, which is something that should never happen anyway as there shouldn't be any hard-coded paths for writing). I do agree that this is more elegant than than chowning `/mnt/` (which would require that `sudo` not require a password, as in our instances, to avoid having to store a root password somewhere). 

@antgonza and @wasade, do you have thoughts about this?

**Comment by wasade** [comment]
root is just any other user, so there won't be any user-based affects on testing simply because of UID. Writing to directories that shouldn't be written to is impossible to test for since it is system dependent, and even the root user cannot write everywhere. However, it is bad practice to run as root when it is not absolutely required: from a system administration standpoint it is inelegant to use root in this context. root passwords should be avoided as well, at least for login (all are systems explicitly do not allow root logins and is standard practice). Using sudo with or without a password does not require root to have a password.

**Comment by antgonza** [comment]
Have you tested that root works? If I remember correctly you will need to
run activate.sh and possibly other things to make it work. Anyway, there
are other two possibilities: like you said, allow ubuntu to read/write in
/mnt/; or that in future releases we make /home/ubuntu/ larger, not sure
how possible is this.

**Comment by jairideout** [comment]
@antgonza I haven't explicitly tested qiime-deploy as root, but I think it would work since root is just another user, and activate.sh is written under the deploy directory (which would be something like /mnt/qiime_software/). I'll go ahead and test it out though.

@wasade I understand it's bad practice to run as root from a sysadmin perspective, but this would only be for "throw-away" instances that are created by Clout purely for testing purposes.

I'm not sure what the best solution is... I see pros/cons for either approach. Let me test qiime-deploy as root and see how that goes, then we can decide from there.

**Comment by wasade** [comment]
we shouldn't promote bad practices...

**Comment by jairideout** [comment]
I don't really see how we're promoting it- Clout users aren't forced to run as root if they don't want to. Also, we're not making our Clout configs publicly available, and we're not making any explicit recommendations to run as root. Just in our case, we simply don't have the hard disk space to test QIIME, PICRUSt, etc.. so I feel we may need that flexibility.

StarCluster uses the same approach with sshmaster: if you don't provide a user via `-u`, it will log in as root.

**Comment by jairideout** [comment]
Tested out qiime-deploy as root under /mnt/ and it works. However, given that I'm the only one who seems to like the idea of running as root, should we just give `ubuntu` write permissions to /mnt/ for now? There may be a less hackish way of doing this once I redesign the file format Clout uses to define test suites, but we could use this workaround for now. Anyone want to make a final call on this?

**Comment by gregcaporaso** [comment]
Given that (1) it works, (2) that users can override to run as a different user if they want to, (3) that the instances are discarded after the tests complete and (4) @wasade's point about the difficultly of testing for writing to directories that "shouldn't" be written to, I think it's worth trying going with this to simplify the writing to `/mnt/`.

**Comment by jairideout** [comment]
Just realized an even better solution to make everyone happy: StarCluster creates a huge area under `/mnt/CLUSTER_USER/`, so we should be able to do everything from `/mnt/ubuntu/` since that directory has read/write permissions. Sorry about noticing this too late! I was using the default StarCluster user `sgeadmin` and didn't notice that an area was being created for the `CLUSTER_USER`.

Even so, I think having the default user set to `root` is okay since it mimics `sshmaster`'s behavior and is one less required option for the `clout` script. We'll continue using `ubuntu` in the nightly tests though.

**Comment by gregcaporaso** [comment]
Sounds good - is that directory created by default? I've never noticed that before.

**Comment by jairideout** [comment]
Yep, it's created by default for the cluster user defined in the StarCluster config. See [here](http://star.mit.edu/cluster/docs/latest/manual/getting_started.html#verify-scratch-space) for more details.
